### ISSUE TITLE
Cannot get StatsD Metrics

### ISSUE THREAD

**Issue by danudell-trustnetworks** [uber/cherami-server#331]
I've noticed that Cherami supports sending stats to a statsd server. From looking through the code i have the following configuration:

```
DefaultServiceConfig:
  ListenAddress: "..."
  RingHosts: "..."
  EnableLimits: true
  Metrics:
    statsd:
      hostPort: "statsd:8125"
      prefix: "ch"
```

And I can see a RuntimeMetricsReporter starts, but because the statsd metrics exporters doesn't log anywhere I can't see why I'm not getting stats appear on the other end. is there a configuration I have missed? 

Cheers,
Dan
